# Generated by Django 6.1 on 2026-08-18 06:10

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taggeditem',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
